apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/argoproj/argo-workflows/manifests/base?ref=v3.1.9
- github.com/argoproj/argo-workflows/manifests/cluster-install/workflow-controller-rbac?ref=v3.1.9
- github.com/argoproj/argo-workflows/manifests/cluster-install/argo-server-rbac?ref=v3.1.9
resources:
- namespace.yaml
- templates.yaml
patchesStrategicMerge:
- config.yaml
namespace: argo